//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Governorate
    {
        public int GovernorateId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string GovernorateName { get; set; }
    
        public virtual Tbl_Country Tbl_Country { get; set; }
    }
}
